# Generated by Django 4.0.3 on 2022-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50, null=True)),
                ('comp_title', models.CharField(max_length=1000, null=True)),
                ('comp_title_two', models.CharField(max_length=1000, null=True)),
                ('comp_details', models.CharField(max_length=2000, null=True)),
                ('comp_details_two', models.CharField(max_length=2000, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('notice', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
