# Generated by Django 4.0.3 on 2022-09-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0002_homedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='comp_details_two',
            field=models.BigIntegerField(max_length=2000, null=True),
        ),
    ]
