# Generated by Django 4.0.3 on 2022-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0003_alter_homedetails_comp_details_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='comp_details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='comp_details_two',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='comp_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='comp_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='comp_title_two',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='notice',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
