# Generated by Django 4.0.5 on 2022-09-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0005_homedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
