<<<<<<< HEAD
# Generated by Django 4.0 on 2022-08-23 05:41
=======
# Generated by Django 4.0.5 on 2022-08-25 17:34
>>>>>>> 41d9295c0f64bf01eddcbcbd4214c8c29997d2a7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(default=True, max_length=25, null=True)),
=======
                ('name', models.CharField(max_length=25)),
>>>>>>> 41d9295c0f64bf01eddcbcbd4214c8c29997d2a7
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('course_number', models.CharField(default=True, max_length=5, null=True)),
                ('course_name', models.CharField(default=True, max_length=40, null=True)),
                ('max_numb_students', models.CharField(default=True, max_length=65, null=True)),
                ('subject_teacher', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administration.instructor')),
=======
                ('course_code', models.CharField(max_length=5, null=True)),
                ('course_name', models.CharField(max_length=40, null=True)),
                ('max_numb_students', models.CharField(max_length=65, null=True)),
                ('instructors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.instructor')),
>>>>>>> 41d9295c0f64bf01eddcbcbd4214c8c29997d2a7
            ],
        ),
    ]
