# Generated by Django 4.0 on 2022-08-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_numb_students',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
