# Generated by Django 4.0.5 on 2022-09-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('section_header', models.CharField(blank=True, max_length=20)),
                ('department_header', models.CharField(blank=True, max_length=20)),
                ('class_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('course', models.CharField(blank=True, max_length=20)),
                ('venue', models.CharField(blank=True, max_length=20)),
                ('instructor', models.CharField(blank=True, max_length=20)),
                ('meeting_timing', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
