# Generated by Django 4.0 on 2022-09-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='course_code',
        ),
    ]
