# Generated by Django 4.0 on 2022-08-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_alter_course_subject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject_teacher',
            new_name='Instructor',
        ),
    ]
